name: C2 BOT

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install requests
      
      - name: Run C2 Bot
        env:
          C2_TOKEN: ${{ secrets.C2_TOKEN }}
          C2_USER: ${{ github.repository_owner }}
          C2_REPO: ${{ github.event.repository.name }}
        run: |
          python c2_bot.py
