name: C2 BOT

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install
        run: pip install requests
      - name: Run
        env:
          C2_TOKEN: ${{ secrets.C2_TOKEN }}
        run: python c2_bot.py
